MAKE = mingw32-make -f Makefile.win

all:	cement-analysis_obj \

cement-analysis_obj:
	echo You need to descend into cement-analysis folder to compile
	echo and install their programs
clean:
	cd cement-analysis; ${MAKE} clean

cleanobj:
	cd cement-analysis;  ${MAKE} cleanobj

install:
	echo "Installing all tools in tools directory"
