MAKE = make
all:	cement-analysis_obj \

cement-analysis_obj:
	cd cement-analysis; ${MAKE} all

clean:
	cd cement-analysis; ${MAKE} clean

cleanobj:
	cd cement-analysis; ${MAKE} cleanobj

install:
	echo "Installing all tools in tools directory"
